theme: jekyll-theme-cayman
title: "Learning From Networks: Algorithms, Theory, & Applications"
description: Larger and larger, more and more sophisticated networks are used in more and more applications. It is well recognized that network data is sophisticated and challenging.
